#!/bin/bash
# The following configuration is an example of how to set up the deployment configuration file.
# This configuration is for deployment using github.com/bufferpunk/deploy-bash. See the project for more details
PROJECT_NAME="Central"
DEPLOY_DIR="~/.central/releases" # The release directory is required. It will be created if it does not exist.
LOG_FILE="logs.log" # for the future
SERVERS="logmachine.org" # list of servers to deploy to. Comma separated. The script will loop through each server and deploy to it.
TYPE="domain"
SERVICES=""
NODE_HOME="./frontend"
SETUP_COMMAND="cd ~/.central/current/frontend && npm run build"
JSHOST="~/.central/current/frontend/src/stores/global.js"

SSH_USER="ubuntu"
SSH_PORT="22"
SSH_KEY="~/.ssh/m_amazon_bp.pem"

log_message() {
  local message="$1"
  local loglevel="$2"
  echo -e "$(date '+%Y-%m-%d %H:%M:%S') - $message" >> "$LOG_FILE"
}

export PROJECT_NAME
export DEPLOY_DIR
export LOG_FILE
export SERVERS
export SERVICES
export TYPE
export NODE_HOME
export JSHOST
export SSH_USER
export SSH_PORT
export SSH_KEY
export SSH_USER
export SSH_PORT
export SSH_KEY
export -f log_message
